# SITE CONFIGURATION
title: 設計者筆記 # your site title
author: jskyzero # You :P
description: > # Meta description of Homepage
  jskyzero's notes about game designer.
# url: "https://jskyzero.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
# baseurl: "/Designer-Notes" # the subpath of your site, e.g. /blog
# img_url: /Designer-Notes/assets/img
url: https://design.jskyzero.com
baseurl: ""
img_url: "/assets/img"
excerpt_separator: <!--more-->

# SEO PLUGIN
social:
  name: jskyzero
  links:
    - https://twitter.com/jskyzero
    # - https://www.facebook.com/ben.balter
    # - https://www.linkedin.com/in/BenBalter
    # - https://plus.google.com/+BenBalter
    - https://github.com/jskyzero
    # - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Daily', link: '/daily'}
  - {name: 'Program', link: 'https://blog.jskyzero.com'}
  - {name: 'Categories', link: '/categories'}
  # - {name: 'About', link: 'https://jskyzero.com'}
  # - {name: 'About', link: '/about'}
  # - {name: 'Contact', link: '/contact'}


tagline: >
  想做遊戲的初衷是『製造歡樂，傳播感動』，將相關的記錄和文章收錄到了這裡。

hero_img: posts/bg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

# for daily
daily:
  tagline: 日常，以及不那麼日常。
  hero_img: posts/bg.she.jpg

email: jskyzero@outlook.com # email for form submission

twitter_username: jskyzero # replace with your_twitter_username or comment to remove link from footer
github_username:  jskyzero # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: designer-notes # to enable comments replace with your_disqus_shortname

google_tag_manager: GTM-NWGMB85 # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:year/:month/:day/:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
